// ==========================================
// ADMIN DASHBOARD LOGIC
// ==========================================

// 1. Auth Check
document.addEventListener("DOMContentLoaded", () => {
    const isAuth = localStorage.getItem("jobreadyAdminAuth");
    if (isAuth !== "true") {
        alert("Access Denied! Please login from the main page.");
        window.location.href = "index.html";
        return;
    }
    
    // Set Date for Report
    document.getElementById("reportDate").innerText = new Date().toLocaleDateString('en-IN');

    loadUsers();
});

// Logout
function logoutAdmin() {
    localStorage.removeItem("jobreadyAdminAuth");
    window.location.href = "index.html";
}

// 2. Load and Display Users
function loadUsers() {
    const tbody = document.getElementById("userTableBody");
    tbody.innerHTML = "";
    
    let users = [];
    try {
        const stored = localStorage.getItem("jobreadyAllUsers");
        if (stored) users = JSON.parse(stored);
    } catch(e) {}

    // Mock Data for Hackathon Demo if empty
    if (users.length === 0) {
        users = [
            { id: 'usr_1', name: "Rahul Sharma", email: "rahul@gmail.com", phone: "9876543210", role: "Software Developer", password: "AutoGenerated!1" },
            { id: 'usr_2', name: "Sneha Patil", email: "sneha@yahoo.com", phone: "9988776655", role: "Data Analyst", password: "AutoGenerated!2" }
        ];
        localStorage.setItem("jobreadyAllUsers", JSON.stringify(users));
    }

    if (users.length === 0) {
        tbody.innerHTML = `<tr><td colspan="5" style="text-align:center; padding:30px;">No registered users found.</td></tr>`;
        return;
    }

    users.forEach(user => {
        const tr = document.createElement("tr");
        tr.innerHTML = `
            <td>
                <strong>${user.name}</strong>
            </td>
            <td>
                <div>${user.email}</div>
                <div style="font-size:12px; color:#64748b; margin-top:4px;">${user.phone || 'N/A'}</div>
            </td>
            <td><span class="role-badge">${user.role || 'Student'}</span></td>
            <td><span style="font-family:monospace; background:#f1f5f9; padding:4px 8px; border-radius:4px;">${user.password || 'N/A'}</span></td>
            <td class="no-print">
                <div class="action-btns">
                    <button class="action-btn edit-btn" onclick="openEditModal('${user.id}')" title="Edit">
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path></svg>
                    </button>
                    <button class="action-btn delete-btn" onclick="deleteUser('${user.id}')" title="Delete">
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg>
                    </button>
                </div>
            </td>
        `;
        tbody.appendChild(tr);
    });
}

// 3. Delete Logic
function deleteUser(id) {
    if(!confirm("Are you sure you want to delete this user?")) return;
    
    let users = JSON.parse(localStorage.getItem("jobreadyAllUsers") || "[]");
    users = users.filter(u => u.id !== id);
    localStorage.setItem("jobreadyAllUsers", JSON.stringify(users));
    
    loadUsers();
}

// 4. Edit Logic
function openEditModal(id) {
    const users = JSON.parse(localStorage.getItem("jobreadyAllUsers") || "[]");
    const user = users.find(u => u.id === id);
    if (!user) return;

    document.getElementById("editUserId").value = user.id;
    document.getElementById("editName").value = user.name || "";
    document.getElementById("editEmail").value = user.email || "";
    document.getElementById("editPhone").value = user.phone || "";
    document.getElementById("editRole").value = user.role || "";

    document.getElementById("editModalOverlay").classList.add("active");
}

function closeEditModal() {
    document.getElementById("editModalOverlay").classList.remove("active");
}

function saveUserEdit() {
    const id = document.getElementById("editUserId").value;
    let users = JSON.parse(localStorage.getItem("jobreadyAllUsers") || "[]");
    
    const index = users.findIndex(u => u.id === id);
    if (index !== -1) {
        users[index].name = document.getElementById("editName").value;
        users[index].email = document.getElementById("editEmail").value;
        users[index].phone = document.getElementById("editPhone").value;
        users[index].role = document.getElementById("editRole").value;
        
        localStorage.setItem("jobreadyAllUsers", JSON.stringify(users));
        closeEditModal();
        loadUsers();
    }
}

// 5. EXPORT TO PDF
function exportToPDF() {
    // Show print header
    document.getElementById("printHeader").style.display = "block";
    
    // Hide action columns temporarily
    const noPrintElements = document.querySelectorAll('.no-print');
    noPrintElements.forEach(el => el.style.display = 'none');

    const element = document.getElementById('printableArea');
    const opt = {
        margin:       0.5,
        filename:     'JobReady_Users_Report.pdf',
        image:        { type: 'jpeg', quality: 0.98 },
        html2canvas:  { scale: 2 },
        jsPDF:        { unit: 'in', format: 'a4', orientation: 'landscape' }
    };

    html2pdf().set(opt).from(element).save().then(() => {
        // Restore elements
        document.getElementById("printHeader").style.display = "none";
        noPrintElements.forEach(el => el.style.display = '');
    });
}

// 6. EXPORT TO EXCEL
function exportToExcel() {
    const users = JSON.parse(localStorage.getItem("jobreadyAllUsers") || "[]");
    
    // Map data for clean Excel export
    const excelData = users.map((u, index) => ({
        "Sr No": index + 1,
        "Full Name": u.name,
        "Email Address": u.email,
        "Phone Number": u.phone,
        "Target Role": u.role,
        "Password (Auto)": u.password,
        "Registration Date": u.registeredAt ? new Date(u.registeredAt).toLocaleDateString() : 'N/A'
    }));

    const worksheet = XLSX.utils.json_to_sheet(excelData);
    const workbook = XLSX.utils.book_new();
    
    // Add Logo Text to first cell workaround (SheetJS doesn't support images in free version easily)
    XLSX.utils.sheet_add_aoa(worksheet, [["JobReady - Registered Users Report"]], { origin: "A1" });
    
    XLSX.utils.book_append_sheet(workbook, worksheet, "Users");
    XLSX.writeFile(workbook, "JobReady_Users_List.xlsx");
}
